### DISCUSSION TITLE
Parameter with a list of pre-defined selectable values

### DISCUSSION THREAD

**Discussion by JMLX42** [juhaku/utoipa#667] [Q&A]
Hi!

I need my OpenAPI definition to feature a `schema` typed as an `array` with a list of (multi)selectable `enum` values:

![image](https://github.com/juhaku/utoipa/assets/998703/33b340ab-6ad7-49f5-b607-1115a499a281)

Here is a corresponding example definition:

```yml
openapi: 3.0.0
info:
  title: Your API
  version: 1.0.0
paths:
  /example:
    get:
      summary: Get examples
      parameters:
        - name: status
          in: query
          description: Status of the example
          required: true
          schema:
            type: array
            items:
              type: string
              enum:
                - active
                - inactive
                - pending
      responses:
        '200':
          description: OK
```

I expected a Rust `enum` to do the job, but I cannot find a way to get the expected result.

Any suggestion?

**Comment by JMLX42** [comment]
My bad... I finally found that a vector of enum does the job:

```rust
use serde::{Serialize, Deserialize};
use utoipa::{OpenApi, ToSchema};

#[derive(OpenApi)]
#[openapi(
    info(description = "My Api description"),
    components(
        schemas(
            MyEnum, Fields, MyEnumVec
        ),
    ),
)]
struct ApiDoc;

#[derive(Serialize, Deserialize, ToSchema)]
enum MyEnum {
    Value1,
    Value2,
    Value3,
}

#[derive(Serialize, Deserialize, ToSchema)]
struct MyEnumVec(#[schema(inline)] Vec<MyEnum>);

#[derive(Serialize, Deserialize, ToSchema)]

struct Fields {
    first_field: Vec<MyEnum>,
}

fn main() {
    let mut doc = ApiDoc::openapi();
    doc.info.title = String::from("My Api");

    println!("{}", ApiDoc::openapi().to_pretty_json().unwrap());
}
```

```yaml
{
  "openapi": "3.0.3",
  "info": {
    "title": "utoipa-test",
    "description": "My Api description",
    "license": {
      "name": ""
    },
    "version": "0.1.0"
  },
  "paths": {},
  "components": {
    "schemas": {
      "Fields": {
        "type": "object",
        "required": [
          "first_field"
        ],
        "properties": {
          "first_field": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/MyEnum"
            }
          }
        }
      },
      "MyEnum": {
        "type": "string",
        "enum": [
          "Value1",
          "Value2",
          "Value3"
        ]
      },
      "MyEnumVec": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/MyEnum"
        }
      }
    }
  }
}
```

![image](https://github.com/juhaku/utoipa/assets/998703/2f2449e0-54f9-4321-b9f2-bb27b9a0ac9a)
