### ISSUE TITLE
Axum example does not work.... still

### ISSUE THREAD

**Issue by ipconfiger** [juhaku/utoipa#1033]
Cargo.toml
```
utoipa = { version = "4.2.3", features = [
    "axum_extras",
    "debug",
    "chrono",
    "time",
    "uuid",
    "decimal",
    "url", ] }
utoipa-swagger-ui = { version = "=7.1.0", features = ["axum",] }
```
Code:
```
use utoipa::OpenApi;
use utoipa_swagger_ui::SwaggerUi;

...

    let app = Router::new()
        .merge(SwaggerUi::new("/api/docs/ui")
            .url("/api/docs/openapi.json", ApiDoc::openapi()))
        .route("/api/docs/openapi.json", get(openapi))
        ...
        .with_state(state);

```

Build result:
```
error[E0277]: the trait bound `Router<_, _>: From<SwaggerUi>` is not satisfied
   --> src/app.rs:50:16
    |
50  |           .merge(SwaggerUi::new("/api/docs/ui")
    |  __________-----_^
    | |          |
    | |          required by a bound introduced by this call
51  | |             .url("/api/docs/openapi.json", ApiDoc::openapi()));
    | |_____________________________________________________________^ the trait `From<SwaggerUi>` is not implemented for `Router<_, _>`, which is required by `SwaggerUi: Into<Router<_, _>>`
    |
    = note: required for `SwaggerUi` to implement `Into<Router<_, _>>`
note: required by a bound in `Router::<S, B>::merge`
```

What i miss?

**Comment by juhaku** [comment]
Full cargo.toml
```toml
[package]
name = "utoipa-test"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tower = "0.5"
utoipa = { version = "4", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "7", features = ["axum"] }
```

Full rust code main.rs
```rust
use std::net::Ipv4Addr;

use axum::{routing, Router};
use tokio::net::TcpListener;
use utoipa::OpenApi;
use utoipa_swagger_ui::SwaggerUi;

#[tokio::main]
async fn main() -> Result<(), std::io::Error> {
    let app: Router = Router::new()
        .route("/health", routing::get(health))
        .merge(SwaggerUi::new("/swagger-ui").url("/api-docs/openapi.json", ApiDoc::openapi()));

    let listener = TcpListener::bind((Ipv4Addr::LOCALHOST, 8080)).await?;
    axum::serve(listener, app).await
}

#[derive(OpenApi)]
#[openapi(paths(health))]
struct ApiDoc;

#[utoipa::path(
    get,
    path = "/health",
    responses(
        (status = OK, description = "Success", body = str)
    )
)]
async fn health() -> &'static str {
    "OK"
}
```
![Screenshot from 2024-09-08 11-11-10](https://github.com/user-attachments/assets/552061a2-574e-40a9-a19b-bdee2dc2af7c)
![image](https://github.com/user-attachments/assets/251165fd-1ef5-4d17-959d-319bddd4ece9)

This will work. Have you tried `cargo clean`. That error indicates that the `SwaggerUi` does not implement axum `Router` trait. However the `utoipa-swagger-ui` does provide this implementation with `axum` feature flag.

Have you tried to debug with `cargo tree --format "{p} {f}"` to see what features gets where?

**Comment by ipconfiger** [comment]
OK, tks, will try it

**Comment by juhaku** [comment]
@ipconfiger  Can this be considered solved?

**Comment by ipconfiger** [comment]
cargo clean works,tks

**Comment by orsenkucher** [comment]
This does not work on
```toml
[dependencies]
axum = { version = "0.7.9" }
tokio = { version = "1", features = ["full"] }
tower = "0.5"
utoipa = { version = "5.3.1", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "9.0.0", features = ["axum"] }
```

error[E0277]: the trait bound `Router<_>: From<SwaggerUi>` is not satisfied
   --> src/main.rs:12:16
    |
12  |         .merge(SwaggerUi::new("/swagger-ui").url("/api-docs/openapi.json", ApiDoc::openapi()));
    |          ----- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `From<SwaggerUi>` is not implemented for `Router<_>`, which is required by `SwaggerUi: Into<Router<_>>`
    |          |
    |          required by a bound introduced by this call
    |
    = note: required for `SwaggerUi` to implement `Into<Router<_>>`
note: required by a bound in `Router::<S>::merge`
