### ISSUE TITLE
http security requirements are missing the `in` field

### ISSUE THREAD

**Issue by irevoire** [juhaku/utoipa#1074]
Hey,

I was trying to use utoipa for Meilisearch.
Currently, we’re writing our own openAPI.yml file by hand and with utoipa I think you’re missing the `in` field while defining API key.
```yml
  securitySchemes:
    apiKey:
      type: http
      in: header
      scheme: bearer
      description: |-
        An API key is a token that you provide when making API calls. Include the token in a header parameter called `Authorization`.

        Example: `Authorization: Bearer 8fece4405662dd830e4cb265e7e047aab2e79672a760a12712d2a263c9003509`
```

https://spec.openapis.org/oas/latest.html#fixed-fields-22
