### ISSUE TITLE
Incomplete spec dump via `to_pretty_json` with auto registered schemas

### ISSUE THREAD

**Issue by leebenson** [juhaku/utoipa#1126]
Calling `openapi::OpenApi.to_pretty_json()` produces an incomplete spec doc when used with schema auto-registration.

It's likely to trip people up following the [readme example](https://github.com/juhaku/utoipa?tab=readme-ov-file#examples).

e.g. something basic like this:

```rust
#[derive(OpenApi)]
#[openapi(
    servers(
        (url = "http://localhost:3000", description = "Local Dev"),
        (url = "https://api.<remote-site>", description = "Remote API"),
    )
)]
pub struct ApiDoc;
```

Will produce this:

```yaml
{
  "openapi": "3.1.0",
  "info": {
    "title": "server",
    "description": "",
    "license": {
      "name": ""
    },
    "version": "0.1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "Local Dev"
    },
    {
      "url": "https://api.<remote-site>",
      "description": "Remote API"
    }
  ],
  "paths": {},
  "components": {}
}
```

A fix is to wrap in the router to ensure routes have been fully initialised:

```rust
let (router, api) = OpenApiRouter::with_openapi(ApiDoc::openapi())
        .merge(api::routes())
        .split_for_parts()
```

... and then call `api.to_pretty_json()`.
