### ISSUE TITLE
Utoipa 5: file upload

### ISSUE THREAD

**Issue by ajacquet-evolis** [juhaku/utoipa#1239]
We are trying to migrate from utoipa version 4.2 to 5.2 .
There is a lot of cool new features (no more aliases etc.) but we can't make the upload of files through swagger-ui work as before.

Currently we have some multi-part structs looking like this:
```rust
#[derive(Debug, TryFromMultipart, ToSchema)]
pub struct MyMultipartStruct {
    other_field: String,
    #[schema(value_type = Vec<u8>, format = Binary)]
    file_field: axum::body::Bytes,
}
```
The path is defined with
```rust
#[utoipa::path(
  ...
  request_body(content=MyMultipartStruct, content_type="multipart/form-data")
  ...
)]
```

The resulting openapi was looking like this:
```yml
MyMultipartStruct:
      type: object
      properties:
        password:
          other_field: string
          nullable: true
        file_field:
          type: string
          format: binary
```

Which resulted in a swagger-ui display with a button to select a file from the filesystem.

---

With utoipa 5.x, the same code generates the following openapi:
```yml
MyMultipartStruct:
      type: object
      properties:
        password:
          other_field: string
          nullable: true
        file_field:
          type: array
          items:
            type: integer
            format: binary
            minimum: 0
```

The resulting swagger-ui is a list of integer to fill instead of file selection.
![image](https://github.com/user-attachments/assets/d0beaa89-75d5-4e96-95b3-8496010a257a)

---

With utoipa 5,2 how are we supposed to do to manage multi-part requests with file upload ?
I tried using `content_media_type ` without success...
