### ISSUE TITLE
The generated spec for an Option field is unpleasant and breaks swift-openapi-generator

### ISSUE THREAD

**Issue by grahamc** [juhaku/utoipa#1260]
The spec that is generated today is:

```yaml
    AuthenticationStatus:
      type: object
      properties:
        token:
          oneOf:
            - type: 'null'
            - "$ref": "#/components/schemas/TokenStatus"
```

Since the token is both `null`able and also not required, the swagger UI double-indicates this in an ugly way, by showing no `*` to say it isn't required, and also showing oneOf null / the object:

![CleanShot 2024-12-26 at 15 15 39@2x](https://github.com/user-attachments/assets/d12661fc-3651-45da-b0ce-be054c1a9e1f)

and in the sample output, it decides to show the `null` option instead a usefully populated example:

![CleanShot 2024-12-26 at 15 16 31@2x](https://github.com/user-attachments/assets/511f31b6-50d1-4137-a16d-ca5d65878499)

and further, the swift openai generator pukes:

> warning: Schema "null" is not supported, reason: "schema type", skipping [context: foundIn=Components.Schemas.AuthenticationStatus (#/components/schemas/AuthenticationStatus)/token]

but this all seems a bit silly anyway, since the field is not marked as required, so we can skip the oneOf null entirely and get better docs, and better examples.

With:

```yaml
    AuthenticationStatus:
      type: object
      required:
      properties:
        token:
          "$ref": "#/components/schemas/TokenStatus"
```

![CleanShot 2024-12-26 at 15 18 00@2x](https://github.com/user-attachments/assets/c84171c3-bff1-4833-923d-60bcdb39d586)

![CleanShot 2024-12-26 at 15 17 51@2x](https://github.com/user-attachments/assets/6522a600-a971-447b-ae11-a3602f66782d)

and finally, the swift generator handles it just fine.
