### ISSUE TITLE
Non-tuple path parameters in axum

### ISSUE THREAD

**Issue by srkaj** [juhaku/utoipa#1302]
We have noticed a discrepancy in how url parameters are detected for the openapi specification.  If we use a tuple, the arguments are auto-detected, but if we use a single parameeter, we seem to need an annotation that I think should no longer be needed because of #1224.

These endpoints work as expected:

```rust
#[utoipa::path(
    get, path = "/{id}",
    params(MyId),  // This is still needed?
)]
async fn one(
    Path(id): Path<MyId>,
) -> Result<Json<MyDTO>> {
    // ...
}

#[utoipa::path(
    get, path = "/{id}", // No "params" here!
)]
async fn other(
    Path((id, subid)): Path<(MyId, SubId)>,
) -> Result<Json<MyDTO>> {
    // ...
}
```

Having a single argument and no "params" annotation, like this endpoint, also works as expected in axum, except it does not get any parameters in the openapi specification / swagger guide:

```rust
#[utoipa::path(
    get, path = "/{id}",
)]
async fn one(
    Path(id): Path<MyId>,
) -> Result<Json<MyDTO>> {
    // ...
}
```

As a workaround, it seems wrapping the parameter in a single-value tuple is enogh to get it to work:

```rust
#[utoipa::path(
    get, path = "/{id}",
)]
async fn one(
    Path((id,)): Path<(MyId,)>,
) -> Result<Json<AudioRoomDTO>> {
    // ...
}
```

Are we missing anything?   Should there be another trait implemented for `MyId` that is somehow implemented for the tuple?  Or is this a bug in utoipa?

# Versions used

According to our Cargo.toml:
```toml
axum = "0.8.1"
utoipa = { version = "5.2.0", features = ["axum_extras", "openapi_extensions", "preserve_order", "uuid"] }
utoipa-axum = "0.2.0"
utoipa-swagger-ui = { version="9.0.0", features = ["axum"] }
```

**Comment by jackjohn7** [comment]
I've encountered this in a project as well.

## Hacky tuple fix mentioned above

This code will generate the parameter in my docs:
```rust
    Path((id,)): Path<(AnnouncementId,)>,
```

```yaml
  /announcements/{id}:
    delete:
      tags:
      - announcements
      operationId: delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/AnnouncementId'
...
```

## Single param

This code will not:
```rust
    Path(id): Path<AnnouncementId>,
```
```yaml
  /announcements/{id}:
    delete:
      tags:
      - announcements
      operationId: delete
...
```

What I noticed was that `String` would not have this problem. It seems to only happen with these custom types like `AnnouncementId` or `MyId`. See the example below with a string:

```rust
    Path(id): Path<String>,
```
```yaml
  /announcements/{id}:
    delete:
      tags:
      - announcements
      operationId: delete
      parameters:
      - name: announcementId
        in: path
        required: true
        schema:
          type: string
...
```

If I however explicitly provide `params(AnnouncementId)` to the `utoipa::path` macro and derive `IntoParams` for `AnnouncementId` providing some name with `into_params(names("announcementId"))`, the resulting parameter in the generated spec is of type `string` rather than `AnnouncementId`.

# Code in question

```rust
#[axum::debug_handler]
#[utoipa::path(
    delete,
    path = "/{id}", tag = "announcements",
    responses(
        (status=OK, body=Announcement, content_type="application/json"),
        (status=404, description="Announcement with provided id does not exists"),
        (status=401, description="User may not delete announcements"),
    )
)]
pub async fn delete(
    State(state): State<Arc<AppState>>,
    HostUser(_u): HostUser,
    Path((id,)): Path<(AnnouncementId,)>,
) -> Result<Json<Announcement>, StatusCode> { ... }
```

[https://github.com/basalt-rs/basalt-server/blob/f906b69486e816d2e4a55af6a90722478385f2e5/basalt-server-lib/src/services/announcements.rs#L90-L124](Source) in PR.

# Versions used

```toml
axum-extra = { version = "0.10.0", features = ["typed-header"] }
axum = { version = "0.8.1", features = ["macros", "ws"] }
utoipa-axum = { version = "0.2.0", features = ["debug"] }
utoipa = { version = "5.4.0", features = [
    "chrono",
    "debug",
    "yaml",
    "axum_extras",
] }
```
