### ISSUE TITLE
Swagger UI not rendering on release build unless debug-embed feature is enabled

### ISSUE THREAD

**Issue by callumadair** [juhaku/utoipa#1315]
As I understand it, swagger ui should build by default if I do not have `debug-embed` enabled when I use `cargo run --release` and should not build in the same `Cargo.toml` file for `cargo run`. Currently without the `debug-embed` feature neither debug nor release builds generate the swagger ui, but with the `debug-embed` feature both work as intended. 

Am I misunderstanding the docs or is this a bug?

```toml
[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
path = "./src/lib.rs"
name = "portfolio_backend_lib"

[[bin]]
path = "./src/main.rs"
name = "portfolio_backend_bin"

[dependencies]
actix-settings = "0.8.0"
actix-web = { version = "4.9.0", features = ["rustls"] }
sea-orm = { version = "1.1.4", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
tracing = "0.1.41"
tracing-actix-web = "0.7.15"
tracing-subscriber = "0.3.19"
utoipa = { version = "5.3.1", features = ["actix_extras"] }
utoipa-actix-web = "0.1.2"
# The swagger UI will not render unless the "debug-embed" feature is enabled, even on release builds
utoipa-swagger-ui = { version = "9.0.0", features = ["actix-web", "debug-embed"] }

[lints]
workspace = true
```
