### ISSUE TITLE
Compilation error in build.rs

### ISSUE THREAD

**Issue by rogerjbos** [juhaku/utoipa#1350]
I am trying to compile my rust API on a new ubuntu server and I am getting this compilation error:

   Compiling utoipa-swagger-ui v9.0.0
error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/utoipa-swagger-ui-9.0.0/build.rs:105:49
    |
105 |                 .ok_or(ZipError::InvalidArchive("invalid path file"))?;
    |                        ------------------------ ^^^^^^^^^^^^^^^^^^^ expected `Cow<'_, str>`, found `&str`
    |                        |
    |                        arguments to this enum variant are incorrect
    |
    = note:   expected enum `Cow<'static, str>`
            found reference `&'static str`
note: tuple variant defined here
   --> /home/ubuntu/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zip-2.5.0/src/result.rs:23:5
    |
23  |     InvalidArchive(Cow<'static, str>),
    |     ^^^^^^^^^^^^^^
help: try wrapping the expression in `std::borrow::Cow::Borrowed`
    |
105 |                 .ok_or(ZipError::InvalidArchive(std::borrow::Cow::Borrowed("invalid path file")))?;
    |                                                 +++++++++++++++++++++++++++                   +

This is happening with both rustc 1.85.1 and 1.84.1 and with version 8 and version 9 of utopia-swagger-ui.  The code compiles fine on my old server.  I have to look into exactly what the differences are.

**Comment by joeymich** [comment]
+1

**Comment by AngelEspinal1** [comment]
I have the same error, but it is solved with the suggestion of the compiler I would like to know when they will integrate the solution.

**Comment by LockedThread** [comment]
+1

**Comment by danyatheslayer** [comment]
+1

**Comment by b-yap** [comment]
+1

**Comment by Power2All** [comment]
+1

**Comment by Esgrove** [comment]
As a temporary fix, one can run `cargo update -p zip --precise 2.4.2` to downgrade the zip version in Cargo.lock

**Comment by Power2All** [comment]
Any update on a v2.5.1 release ?

**Comment by incker** [comment]
+1

**Comment by imokoi** [comment]
+1

**Comment by Van4ooo** [comment]
+1

**Comment by jcobins** [comment]
+1

**Comment by ianthetechie** [comment]
Just hit this as well. If you don't want to pin an old zip library, you can instead pin a commit like this:

```toml
utoipa = { git = "https://github.com/juhaku/utoipa.git", rev = "ca6b2a5" }
# Temporarily pinning to a newer commit since a release isn't yet out to address https://github.com/juhaku/utoipa/issues/1350.
utoipa-swagger-ui = { git = "https://github.com/juhaku/utoipa.git", rev = "ca6b2a5", features = ["axum"] }
```

Note that you need to do this for the main crate and any other related utoipa crates, or else you'll get even *more* confusing compiler errors :)

Hopefully we can get a release soon.
