### ISSUE TITLE
Is there a way to specify enum as integer type?

### ISSUE THREAD

**Issue by DriLLFreAK100** [juhaku/utoipa#441]
Good day,

I would like to check if there is a way to generate `enum` as `integer` type in the Open API doc. Also, is there any way to append custom fields into the generated doc such as the `x-enum-varnames` in the example below.

For example, if we have a `Status` enum as such
```rust
#[derive(ToSchema)]
pub enum Status {
    InProgress,
    Done,
    Cancel,
}
```

Is there any way to generate it into the following?

```yaml
Status:
  type: integer
  enum: [0, 1, 2]
  x-enum-varnames: [InProgress, Done, Cancel]
```

Thank you very much in advance!
