### ISSUE TITLE
Unable to host swagger-ui on root URL with Axum

### ISSUE THREAD

**Issue by Sh1nku** [juhaku/utoipa#628]
Seems that there is an problem when trying to host swagger-ui on the root URL with axum.
```rust
let app = Router::new()
        .merge(SwaggerUi::new("/").url("/openapi.json", ApiDoc::openapi()))
```

https://github.com/juhaku/utoipa/blob/970e10f4203edc8af68c78a009dbb8dc935703bb/utoipa-swagger-ui/src/axum.rs#L49-L57

A redirect from `/` to `//` is created, and the other routes also become incorrect

**Comment by qsantos** [comment]
Minimal working example:
```rust
// src/main.rs

use axum::{routing::get, Router};
use utoipa::OpenApi;
use utoipa_swagger_ui::SwaggerUi;

#[utoipa::path(get, path = "/hello-world")]
pub async fn hello_world() -> &'static str {
    "Hello, World!"
}

#[tokio::main]
async fn main() {
    #[derive(OpenApi)]
    #[openapi(paths(hello_world))]
    struct ApiDoc;

    let app = Router::new()
        .merge(SwaggerUi::new("/").url("/openapi.json", ApiDoc::openapi()))
        .route("/hello-world", get(hello_world));

    axum::Server::bind(&"127.0.0.1:3000".parse().unwrap())
        .serve(app.into_make_service())
        .await
        .unwrap();
}
```
and
```toml
# Cargo.toml

[package]
name = "dloisirs"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.18" }
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread", "fs"] }
utoipa = { version = "3.3.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "3.1.3", features = ["axum"] }
```
The Swagger UI is served on `http://127.0.0.1:3000//`, but `http://127.0.0.1:3000/` returns `303 See Other` with `location: //`. Note that this does not count as a redirection and is not followed by user agents.

Using `SwaggerUi::new("/")` or `url("/openapi.json", ApiDoc::openapi())` result respectively in:
```
Paths must start with a `/`. Use "/" for root routes
```
and
```
Paths must start with a `/`
```
