### ISSUE TITLE
Params Vec<String> are not passed to swaggerUI correctly 

### ISSUE THREAD

**Issue by DerZwergGimli** [juhaku/utoipa#806]
```rs
    #[derive(Debug, Deserialize, IntoParams)]
    pub struct VecTEST {
        mint_assets: Vec<std::string::String>,
    }

  #[utoipa::path(
    get,
    path = "/vec_test",
    params(VecTEST),
    responses(
    (status = 200, description = "List todos successfully")
    )
    )]
    pub async fn vec_test(query: VecTEST) -> Result<impl Reply, Infallible> {
        Ok(warp::reply::json(&json!(query.mint_assets)))
    }
````

```toml
utoipa = { version = "4.1.0", features = ["chrono"] }
utoipa-swagger-ui = "4.0.0"
```

results in this swagger-ui:

![image](https://github.com/juhaku/utoipa/assets/35138004/d5e840a2-0ab9-40c8-ab26-c96a3cd44e74)
