### ISSUE TITLE
Using #[schema(title = ...)] does not work for new type / tuple structs of type Vec<T>

### ISSUE THREAD

**Issue by pdavid31** [juhaku/utoipa#850]
Let me start of by saying: Thank you for your great work on this crate.

Something that I noticed is that using `#[schema(title = "...")]` does not seem to have an effect on tuple structs containing vectors.
I created a minimal example to reproduce the issue.

```toml
[package]
name = "utoipa-test"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.1"
utoipa = "4.2.0"
utoipa-swagger-ui = { version = "6.0.0", features = ["actix-web"] }
```

```rust
use std::{io::Error, net::Ipv4Addr};

use actix_web::{App, HttpServer};
use utoipa::{OpenApi, ToSchema};
use utoipa_swagger_ui::SwaggerUi;

#[derive(ToSchema)]
#[schema(title = "This is an integer using the new type idiom / tuple struct")]
pub struct NewTypeInteger(Vec<i64>);

#[derive(ToSchema)]
#[schema(title = "This is an integer using a regular struct")]
pub struct NamedFieldInteger {
    i: Vec<i64>,
}

#[derive(OpenApi)]
#[openapi(
    info(title = "Minimal example",),
    components(schemas(NewTypeInteger, NamedFieldInteger))
)]
struct ApiDoc;

#[actix_web::main]
async fn main() -> Result<(), Error> {
    HttpServer::new(move || {
        App::new().service(
            SwaggerUi::new("/swagger-ui/{_:.*}").url("/api-docs/openapi.json", ApiDoc::openapi()),
        )
    })
    .bind((Ipv4Addr::UNSPECIFIED, 8080))?
    .run()
    .await
}
```

The output is the following:

![image](https://github.com/juhaku/utoipa/assets/32905212/8e572393-5969-48a8-8b49-5fc4e2a41bd5)
