### ISSUE TITLE
required cannot be set for Header param

### ISSUE THREAD

**Issue by tsauerwein** [juhaku/utoipa#857]
I'm trying to define an optional request header like this:

``` 
#[utoipa::path(
    put,
    path = "/some-path",
    params(
        (
            "X-Request-ID" = String,
            Header,
            required = false,
            deprecated = false,
            description = "...."
        )
    ),
...
)]
```

But I get the following error message that `required` is not allowed:

```
error: unexpected attribute: required, expected any of: style, explode, allow_reserved, example, deprecated, description, format, write_only, read_only, nullable, xml, multiple_of, maximum, minimum, exclusive_maximum, exclusive_minimum, max_length, min_length, pattern, max_items, min_items
  --> api/src/some-file.rs:40:13
   |
40 |             required = false,
   |             ^^^^^^^^

```

Am I doing something wrong? For now, I am using a modifier to set `required` to `false`, but it would be nice to directly set it in the `params` definition.

**Comment by kdopen** [comment]
Just went through this with query params. Try changing the header type to `Option<String>`

**Comment by kdopen** [comment]
Yep, just checked (as I'm about to work on the same thing). This

```
    ...
    params(
        ("X-Request-ID" = Option<String>, Header, description = "Optional header"),
        ("X-Required-ID" = String, Header, description = "required header"),
    )
```

gave me (in swagger-ui) one optional and one required header as expected.

**Comment by juhaku** [comment]
Yup, that's the way. Closed as solved.

**Comment by avandecreme** [comment]
The above example generate the following yaml:

```yaml
      parameters:
      - name: X-Request-ID
        in: header
        description: Optional header
        required: false
        schema:
          type:
          - string
          - 'null'
      - name: X-Required-ID
        in: header
        description: required header
        required: true
        schema:
          type: string
```

Having `null` as a type for a header is incorrect in my opinion.
