### ISSUE TITLE
Wrap property example value in double quotes to avoid hex string being evaluated as a number?

### ISSUE THREAD

**Issue by Flugplatz** [juhaku/utoipa#875]
I have a property definition like below with an example hexadecimal string, because the example field is not quoted the swagger UI interprets this as a decimal string instead of the raw hexadecimal string which I want.

**Example output:**
```yaml
      properties:
        sellToken:
          type: string
          description: Address of token sold.
          example: 0x6810e776880c02933d47db1b9fc05908e5386b96
```

**Wanted output:**
```yaml
      properties:
        sellToken:
          type: string
          description: Address of token sold.
          example: "0x6810e776880c02933d47db1b9fc05908e5386b96"
```

The rust code which generates this is below, i've tried multiple combinations of wrapping the example string in single/double quotes (and inside a json! macro), but this adds **multiple** quotes (ie. '"0x6810e776880c02933d47db1b9fc05908e5386b96"') and makes the value broken in swagger as a raw (unquoted string) is required.

```rust
    /// Address of token sold.
    #[schema(value_type = String, example = "0x6810e776880c02933d47db1b9fc05908e5386b96")]
    pub sell_token: H160,
```

Can someone help me quote this string in the produced yaml?

Thanks,
Matt
