### ISSUE TITLE
Summary/Description Generation Issue with Multiline First Sentences.

### ISSUE THREAD

**Issue by dadepo** [juhaku/utoipa#942]
In 5aa974990f19c7e2073c70695b206e4a3fa4072e a change was introduced to skip the first line in the description. 

The only downside to this is that, when the first line spans more than one line, the generated openapi is made meaningless because the first line is removed. 

For example given: 

```
/// A very long text describing the function that is being documented, but it is
/// quite complicated the first sentence spans to the second line.
```

The generated spec will be

```yaml
  summary: A very long text describing the function that is being documented, but it is
  description: |-
       quite complicated the first sentence spans to the second line.
```

Making both the summary and description meaningless.

**Comment by juhaku** [comment]
Thanks for noticing, it seems that long paragraphs are not taken in account when separating the description and summary in that specific commit. I'll add it to the todo list and fix this as one of the next things.

**Comment by Thomasdezeeuw** [comment]
Thanks for the quick fix @juhaku

**Comment by Thomasdezeeuw** [comment]
The problem seems to be back/not fixed. Using Utoipa v4.2.3, utoipa-gen v4.3.0.

The following Rust:

```rust
/// Reset ping counts for all reviewers. It will recalculate the ping counts for
/// all reviewers, not considering spent pings.
#[utoipa::path(
  // ...
)]
#[post("/api/v0/repositories/{repo_id}/reset-pings")]
pub async fn reset_pings()
```

Creates:

```yaml
  /api/v0/repositories/{repo_id}/reset-pings:
    post:
      tags:
      - repositories
      summary: Reset ping counts for all reviewers. It will recalculate the ping counts for
      description: |-
        all reviewers, not considering spent pings.
```

The summary is cut off at the line end, but the sentence continues on the next line.
