### ISSUE TITLE
Multipart formdata file upload 

### ISSUE THREAD

**Issue by wangjia184** [juhaku/utoipa#960]
### Version

```toml
rocket = { version = "0.5.1", features = ["json"] }
utoipa = "4.2.3"
utoipa-swagger-ui = { version = "7.1.0", features = ["rocket"] }
utoipa-rapidoc = { version = "4.0.0", features = ["rocket"] }
```

###  Code to reproduce

```
    #[derive(FromForm, ToSchema)]
    pub(crate) struct SamPayload<'f> {
        #[schema(value_type = String, format = Binary)]
        image: TempFile<'f>,
    }

    #[utoipa::path(
        post,
        path = "/api/model/sam",
        request_body( content_type = "multipart/formdata", content = SamPayload) ,
        responses(
            (status = 200, description = "", content_type = "application/json"),
            (status = 500, description = "Internal server error")
        )
    )]
    #[post("/model/sam", data = "<form>")]
    pub(crate) async fn segment_anything(
        _basic_auth: RequireBasicAuth,
        form: Form<SamPayload<'_>>,
    ) -> std::io::Result<String> {
        // ...
    }
```

###  Issue

Swagger UI looks ok

![image](https://github.com/juhaku/utoipa/assets/2765840/3ba0f5bc-613e-4f87-9013-e9baea4bf0a9)

But when click `Execute` button,  the image is not sent as file.
![image](https://github.com/juhaku/utoipa/assets/2765840/6a540e9f-c83b-401c-b1c5-969b3ef337a1)

```bash
curl -X 'POST' \
  'http://127.0.0.1:8001/api/model/sam' \
  -H 'accept: */*' \
  -H 'Content-Type: multipart/formdata' \
  -d '{"image":{}}'
```
