### ISSUE TITLE
`#[schema(...)]` (exclusive_)maximum and (exclusive_)minimum error with negative values

### ISSUE THREAD

**Issue by kyle-mccarthy** [juhaku/utoipa#994]
For some reason, the error is only appearing in rust-analyzer diagnostic output (in both vscode and zed) but `cargo check` passes.

It seems like the `-` token is being parsed as punctuation rather than part of the number.

Repro:

```toml
[package]
name = "utoipa-repro"
version = "0.1.0"
edition = "2021"

[dependencies]
utoipa = { version = "5.0.0-alpha.1" }
```

```rust
use utoipa::ToSchema;

#[derive(Debug, ToSchema)]
pub struct Example {
    #[schema(minimum = -2.0, maximum = 2.0, nullable)]
    pub float_value: f32,
}
```

![image](https://github.com/user-attachments/assets/5edea522-a202-4ebc-adaf-bbadd4386de6)

Relevant part of the token stream:

```
TokenStream [
    Ident {
        ident: "minimum",
        span: SpanData { range: 61..68, ... },
    },
    Punct {
        ch: '=',
        spacing: Alone,
        span: SpanData { range: 69..70, ... },
    },
    Punct {
        ch: '-',
        spacing: Alone,
        span: SpanData { range: 71..72, ... },
    },
    Literal {
        kind: Float,
        symbol: "2.0",
        suffix: None,
        span: SpanData { range: 72..75, ... },
    },
    ...
```
